import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

/**
 * DocumentEditService — Handles all VS Code document modifications.
 */
export class DocumentEditService {

    /**
     * Replaces the class value in the active editor with the new class name.
     *
     * @param editor       The active text editor
     * @param line         The line number containing the class attribute
     * @param startChar    The start character index of the class value
     * @param endChar      The end character index of the class value
     * @param newClassName The replacement class name
     */
    async replaceClassAttribute(
        editor: vscode.TextEditor,
        line: number,
        startChar: number,
        endChar: number,
        newClassName: string
    ): Promise<boolean> {
        const range = new vscode.Range(
            new vscode.Position(line, startChar),
            new vscode.Position(line, endChar)
        );

        const success = await editor.edit((editBuilder) => {
            editBuilder.replace(range, newClassName);
        });

        return success;
    }

    /**
     * Appends a CSS @apply rule to the target stylesheet file.
     * Creates the file and its parent directories if they don't exist.
     *
     * @param workspaceRoot The workspace root path
     * @param relativePath  The relative path to the CSS file
     * @param cssContent    The CSS content to append
     * @returns             The absolute path of the modified/created CSS file
     */
    async appendToStylesheet(
        workspaceRoot: string,
        relativePath: string,
        cssContent: string
    ): Promise<string> {
        const absolutePath = path.join(workspaceRoot, relativePath);
        const dirPath = path.dirname(absolutePath);

        // Ensure directory structure exists
        if (!fs.existsSync(dirPath)) {
            fs.mkdirSync(dirPath, { recursive: true });
        }

        // Create with header comment if file doesn't exist
        if (!fs.existsSync(absolutePath)) {
            const header = [
                '/* ==========================================================================',
                '   Extracted Tailwind CSS Utility Classes',
                '   Generated by Shrink Tailwind Class extension',
                '   ========================================================================== */',
                '',
                '',
            ].join('\n');

            fs.writeFileSync(absolutePath, header + cssContent, 'utf8');
        } else {
            // Append with a separator newline
            const existingContent = fs.readFileSync(absolutePath, 'utf8');
            const separator = existingContent.endsWith('\n') ? '\n' : '\n\n';
            fs.writeFileSync(absolutePath, existingContent + separator + cssContent, 'utf8');
        }

        return absolutePath;
    }

    /**
     * Opens the CSS file and scrolls to the newly appended content.
     *
     * @param filePath The absolute path of the CSS file
     */
    async openAndRevealCssFile(filePath: string): Promise<void> {
        const uri = vscode.Uri.file(filePath);
        const document = await vscode.workspace.openTextDocument(uri);
        const editor = await vscode.window.showTextDocument(document, {
            viewColumn: vscode.ViewColumn.Beside,
            preserveFocus: true,
        });

        // Scroll to the bottom where the new rule was appended
        const lastLine = document.lineCount - 1;
        const range = new vscode.Range(lastLine, 0, lastLine, 0);
        editor.revealRange(range, vscode.TextEditorRevealType.InCenter);
    }

    /**
     * Prompts the user to choose or create a CSS file for the extracted classes.
     *
     * @param workspaceRoot   The workspace root path
     * @param defaultPath     The configured default CSS file path
     * @returns               The chosen relative path or undefined if cancelled
     */
    async promptForCssFile(
        workspaceRoot: string,
        defaultPath: string
    ): Promise<string | undefined> {
        const absoluteDefault = path.join(workspaceRoot, defaultPath);
        const fileExists = fs.existsSync(absoluteDefault);

        const items: vscode.QuickPickItem[] = [];

        if (fileExists) {
            items.push({
                label: `$(file) ${defaultPath}`,
                description: 'Configured target file (exists)',
                detail: absoluteDefault,
            });
        } else {
            items.push({
                label: `$(new-file) ${defaultPath}`,
                description: 'Configured target file (will be created)',
                detail: absoluteDefault,
            });
        }

        items.push({
            label: '$(folder-opened) Browse for a CSS file...',
            description: 'Choose a different file',
        });

        const selection = await vscode.window.showQuickPick(items, {
            placeHolder: 'Where should the extracted classes be saved?',
        });

        if (!selection) {
            return undefined;
        }

        if (selection.label.includes('Browse')) {
            const fileUri = await vscode.window.showSaveDialog({
                defaultUri: vscode.Uri.file(path.join(workspaceRoot, 'src/styles')),
                filters: { 'CSS Files': ['css'] },
                title: 'Choose CSS file for extracted classes',
            });

            if (!fileUri) {
                return undefined;
            }

            return path.relative(workspaceRoot, fileUri.fsPath);
        }

        return defaultPath;
    }
}
